defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: eval_rollout
- hardware: atos
- graph: processor_only
- model: gnn
- training: default
- _self_


### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

diagnostics:
  plot:
    enabled: False
hardware:
  files:
    graph: graph_enc_proc_dec_${data.resolution}.pt
model:
  num_channels: 4
dataloader:
  limit_batches:
    training: 5
    validation: 5
training:
  max_epochs: 1
