defaults:
  - hardware: atos
  - data: zarr
  - dataloader: default
  - model: transformer
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

experiment_name: 'aifs_debug'
source_tracking_uri: ${hardware.paths.logs.mlflow}
dest_tracking_uri: 'https://mlflow.copernicus-climate.eu/'
run_id: bf8bafae3cad43299ea9b5dc9e84905f
export_deleted_runs: False
