defaults:
  - hardware: atos
  - data: observations
  - dataloader: default
  - model: gnn
  - graph: multi_scale
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

diagnostics:
  log:
    mlflow:
      enabled: False
      offline: False
      experiment_name: 'aifs_era+obs'
  plot:
    enabled: False
hardware:
  files:
    graph: debug_obs_graph.pt
model:
  num_channels: 128
dataloader:
  batch_size:
    training: 1
    validation: 1
    test: 1
    predict: 1
  limit_batches:
   training: 10
   validation: 10
training:
  max_epochs: 5
  multistep_input: 1
